services:
    yandex.metrica.api:
        class: AppBundle\Service\YandexMetrikaApi
        arguments: ["%yan_metrika_access_token%", "%yan_metrika_url_api%", "%yan_metrika_counter_id%"]
        public: true